config/routes.rb
Rails.application.routes.draw do
  root to: "welcome#home", as: "login_form"

  scope :users do
    get "/home", to: "users#home", as: "users_home"
    get "/search", to: "users#search", as: "users_search"
  end
  resources :users, only: [:index, :new, :show, :create]

  post "/login", to: "welcome#login", as: "login"
  get "/logout", to: "welcome#logout", as: "logout"

  scope :books do
    get "/search", to: "books#search", as: "books_search"
    get "/list_search", to: "books#list_search", as: "books_list_search"
    get "/:id/setup-trade", to: "books#setup_trade", as: "setup_trade"
    get "/:id/remove-trade", to: "books#remove_trade", as: "remove_trade"
  end

  resources :books, only: [:create, :new, :show, :destroy, :index] do
    resources :reviews, shallow: true
  end

  get "/shelf", to: "books#shelf", as: "shelf"
end

app/models/user.rb
# frozen_string_literal: true

# Classe livro responsavel pelas validacoes e relacionamentos dos objetos livro
class User < ApplicationRecord
  has_many :books, dependent: :destroy
  has_many :reviews, dependent: :destroy

  validates :name, presence: true, length: {maximum: 15}
  validates :nickname, uniqueness: true, presence: true, length: {maximum: 5}
  validates :password, presence: true, length: {minimum: 4}
  validates :phone, presence: true
end

app/controllers/user_controller.rb
# frozen_string_literal: true

class UserController < ApplicationController
  def index
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    @user.save
    login_user(@user)
    redirect_to user_home_path
  end

  def show
    @user = User.find(params[:id])
  end

  def user_search
  end

  private

  def user_params
    params.require(:user).permit(:name, :password, :nickname, :phone)
  end
end

app/controllers/users_controller.rb
# frozen_string_literal: true

# Classe controlodora das acoes de usuario
class UsersController < ApplicationController
  skip_before_action :verify_logged_in, only: %i[new create]

  # Renderiza o form de busca por usuario
  def index
  end

  # Renderiza o form de criacao de usuario
  def new
    @user = User.new
  end

  # Adiciona usuario ao banco de dados
  def create
    @user = User.new(user_params)
    if @user.save
      login_user(@user)
      redirect_to users_home_path
    else
      render :new
    end
  end

  # Exibe detalhes do usuario de acordo com o parametro :id
  def show
    @user = User.find(params[:id])
  end

  # Busca usuario de acordo com o parametro :nickname
  def search
    user = User.find_by nickname: params[:nickname]
    if user
      redirect_to user_path(user)
    else
      render :index, error: "usuario não encontrado"
    end
  end

  # Renderiza a home do usuario
  def home
  end

  private

  # Filtro que impede uma requisicao com parametros indesejados para usuario
  def user_params
    params.require(:user).permit(:name, :password, :nickname, :phone)
  end
end

app/helpers/user_helper.rb
# frozen_string_literal: true

module UserHelper
end

app/views/users/home.html.erb
<div class="container">
  <div class="section-title">
    <h1>Home</h1>
  </div>
  <div class="row center-content">
    <ul class="list-group col-md-6">
      <li class="list-group-item"><%= link_to "Estante de livros", shelf_path %></li>
      <li class="list-group-item"><%= link_to "Cadastrar livros", new_book_path %></li>
      <li class="list-group-item"><%= link_to "Buscar livros", books_search_path %></li>
      <li class="list-group-item"><%= link_to "Buscar usuários", users_search_path %></li>
    </ul>
  </div>
</div>

app/views/users/index.html.erb
<div class="container input-form">
  <div class="section-title">
    <h1>Busca de usuário por apelido</h1>
  </div>
  <%= form_tag users_search_path, class: "row", method: "get" do %>
    <div class="form-group col-md-6 offset-md-3">
      <%= label_tag(:nickname, "Apelido:") %>
      <%= text_field_tag(:nickname, "", class: "form-control") %>
    </div>
    <div class="col-md-2 offset-md-3">
      <%= submit_tag("Buscar", class: "btn btn-primary") %>
    </div>
  <% end %>
</div>

app/views/users/new.html.erb
<div class="container center-content">
  <%= form_for @user, url: users_path, html: { class: "row" } do |f| %>
    <% if @user.errors.any? %>
      <div class="alert alert-danger col-md-4 offset-md-4" role="alert">
        <h2><%= pluralize(@user.errors.count, "erro") %> <%= "encontrado".pluralize(@user.errors.count)%>:</h2>

        <ul>
        <% @user.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
      </div>
    <% end %>
    <h4 class="col-md-6 offset-md-3 text-center"> Cadastro </h4>
    <div class="form-group col-md-6 offset-md-3">
      <%= f.label :name, 'Nome' %>
      <%= f.text_field :name , class: "form-control" %>
    </div>
    <div class="form-group col-md-6 offset-md-3">
      <%= f.label :nickname, 'Apelido' %>
      <%= f.text_field :nickname , class: "form-control" %>
    </div>
    <div class="form-group col-md-6 offset-md-3">
      <%= f.label :phone, 'Telefone' %>
      <%= f.telephone_field :phone , class: "form-control" %>
    </div>
    <div class="form-group col-md-6 offset-md-3">
      <%= f.label :password, 'Senha' %>
      <%= f.password_field :password , class: "form-control" %>
    </div>
    <div class="col-md-2 offset-md-3">
      <%= f.submit "Cadastrar", class: "btn btn-primary" %>
    </div>
  <% end %>
</div>

app/views/users/show.html.erb
<div class="container" style="height: 100%;">
  <div class="section-title">
    <h1>Perfil de <%= @user.name %></h1>
  </div>
  <div class="row col-md-12" style="align-items: center;">
    <div class="card offset-md-3 col-md-6">
      <ul class="list-group list-group-flush">
        <li class="list-group-item"><strong>Apelido:</strong> <%= @user.nickname %></li>
        <li class="list-group-item"><strong>Telefone:</strong> <%= @user.phone %></li>
      </ul>
    </div>
  </div>
</div>