config/routes.rb
Rails.application.routes.draw do
  root to: "welcome#home", as: "login_form"

  scope :users do
    get "/home", to: "users#home", as: "users_home"
    get "/search", to: "users#search", as: "users_search"
  end
  resources :users, only: [:index, :new, :show, :create]

  post "/login", to: "welcome#login", as: "login"
  get "/logout", to: "welcome#logout", as: "logout"

  scope :books do
    get "/search", to: "books#search", as: "books_search"
    get "/list_search", to: "books#list_search", as: "books_list_search"
    get "/:id/setup-trade", to: "books#setup_trade", as: "setup_trade"
    get "/:id/remove-trade", to: "books#remove_trade", as: "remove_trade"
  end

  resources :books, only: [:create, :new, :show, :destroy, :index] do
    resources :reviews, shallow: true
  end

  get "/shelf", to: "books#shelf", as: "shelf"
end

app/controllers/welcome_controller.rb
# frozen_string_literal: true

# Classe controladora responsavel pelas acoes de controle de acesso e acoes de usuarios
# nao logados no sistema
class WelcomeController < ApplicationController
  skip_before_action :verify_logged_in, only: %i[home login]

  # Home do sistema primeira pagina que o usuario entra em contato
  def home
  end

  # Acao que define o usuario atual de acordo com os parametros post
  def login
    user = User.find_by(login_params)

    if user.present?
      login_user(user)
      redirect_to users_home_path
    else
      redirect_to login_form_path, error: "Login inválido"
    end
  end

  # Termina sessao do usuario logado
  def logout
    logout_user
    redirect_to login_form_path, success: "Você saiu com sucesso"
  end

  # Filtro que impede uma requisicao com parametros que nao desejamos para login
  def login_params
    params.require(:login).permit(:nickname, :password)
  end
end

app/helpers/welcome_helper.rb
# frozen_string_literal: true

module WelcomeHelper
end

app/views/welcome/home.html.erb
<div class="container">
  <div class="section-title">
    <h1> Loginzinho </h1>
  </div>
  <%= form_for :login, url: login_path, html: { class: "row" } do |f| %>
    <div class="form-group col-md-6 offset-md-3">
      <%= f.label :nickname, "Apelido" %>
      <%= f.text_field :nickname , class: "form-control" %>
    </div>
    <div class="form-group col-md-6 offset-md-3">
      <%= f.label :password, "Senha" %>
      <%= f.password_field :password , class: "form-control" %>
    </div>
    <div class="col-md-2 offset-md-3">
      <%= f.submit "Entrar", class: "btn btn-primary" %>
    </div>
    <div class="col-md-2 offset-md-2 text-right">
      <%= link_to "Cadastrar-se", new_user_path %>
    </div>
  <% end %>
</div>