config/routes.rb
Rails.application.routes.draw do
  root to: "welcome#home", as: "login_form"

  scope :users do
    get "/home", to: "users#home", as: "users_home"
    get "/search", to: "users#search", as: "users_search"
  end
  resources :users, only: [:index, :new, :show, :create]

  post "/login", to: "welcome#login", as: "login"
  get "/logout", to: "welcome#logout", as: "logout"

  scope :books do
    get "/search", to: "books#search", as: "books_search"
    get "/list_search", to: "books#list_search", as: "books_list_search"
    get "/:id/setup-trade", to: "books#setup_trade", as: "setup_trade"
    get "/:id/remove-trade", to: "books#remove_trade", as: "remove_trade"
  end

  resources :books, only: [:create, :new, :show, :destroy, :index] do
    resources :reviews, shallow: true
  end

  get "/shelf", to: "books#shelf", as: "shelf"
end

app/models/book.rb
# frozen_string_literal: true

# Classe livro responsavel pelas validacoes e relacionamentos dos objetos livro
class Book < ApplicationRecord
  belongs_to :user
  has_many :reviews, dependent: :destroy

  validates :title, uniqueness: true

  validates :title, presence: true
  validates :author, presence: true
  validates :code, presence: true, numericality: {only_integer: true}, length: {maximum: 5}
  validates :publication_date, presence: true
  validates :genre, presence: true, inclusion: {in: %w[EPOPEIA CONTO NOVELA ENSAIO ROMANCE]}
  validate :book_count, if: ->(obj) { obj.user.present? }

  # Validacao da quantidade limite de livros pro usuario
  def book_count
    errors.add(:base, "Limite de 10 livros cadastrados") if user.books.count > 9
  end
end

app/controllers/books_controller.rb
# frozen_string_literal: true

# Classe controladora responsavel pelas acoes das resenhas
class BooksController < ApplicationController
  # Renderiza o form de criacao de livro
  def new
    @book = Book.new
  end

  # Cadastra o livro no banco de dados
  def create
    @book = Book.new(book_params)
    @book.user = current_user

    if @book.save
      redirect_to @book, success: "Livro foi cadastrado com sucesso"
    else
      render :new
    end
  end

  # Deleta o livro especificado pelo parametro :id se pertencer ao usuario logado
  def destroy
    book = Book.find(params[:id])

    if (book.user == current_user) && book.destroy
      redirect_to shelf_path, success: "Livro deletado com sucesso"
    else
      redirect_to shelf_path, error: "Ops! parece que ocorreu um erro"
    end
  end

  # Exibe livro pelo param :id
  def show
    @book = Book.find(params[:id])
  end

  # Busca livros do usuario logado e renderiza estante do usuario
  def shelf
    @books = current_user.books
  end

  # Renderiza formulario de busca de livros
  def search
  end

  # Busca livros pelo titulo e renderiza a lista de livros disponiveis encontrados
  def list_search
    @books = Book.where(tradable: true).where("title LIKE ?", "%#{params[:title]}%")
  end

  # Define atributo :tradable do livro com true
  def setup_trade
    book = Book.find(params[:id])
    book.tradable = true

    if book.save
      redirect_to shelf_path, success: "Livro foi disponibilizado para troca"
    else
      redirect_to shelf_path, error: "Ops! parece que ocorreu um erro"
    end
  end

  # Define atributo do livro :tradable como falso
  def remove_trade
    book = Book.find(params[:id])
    book.tradable = false

    if book.save
      redirect_to shelf_path, success: "Livro foi removido de trocas"
    else
      redirect_to shelf_path, error: "Ops! parece que ocorreu um erro"
    end
  end

  private

  # Filtro que impede uma requisicao com parametros que nao desejamos para login
  def book_params
    params.require(:book).permit(:title, :author, :publication_date, :code, :genre)
  end
end

app/views/books/_form.html.erb
<div class="container">
  <%= form_with(model: book, local: true) do |form| %>
    <div class="row">
      <% if book.errors.any? %>
        <div class="alert alert-danger col-md-4 offset-md-4" role="alert">
          <h2><%= pluralize(book.errors.count, "erro") %> <%= "encontrado".pluralize(book.errors.count)%>:</h2>

          <ul>
          <% book.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
          </ul>
        </div>
      <% end %>

      <div class="form-group col-md-6 offset-md-3">
        <%= form.label :title, 'Título' %>
        <%= form.text_field :title, class: "form-control" %>
      </div>

      <div class="form-group col-md-6 offset-md-3">
        <%= form.label :author, 'Autor' %>
        <%= form.text_field :author, class: "form-control" %>
      </div>

      <div class="form-group col-md-6 offset-md-3">
        <%= form.label :publication_date, 'Data de Publicação' %>
        <%= form.date_select :publication_date, class: "form-control" %>
      </div>

      <div class="form-group col-md-6 offset-md-3">
        <%= form.label :code, 'Código' %>
        <%= form.text_field :code, class: "form-control" %>
      </div>

      <div class="form-group col-md-6 offset-md-3">
        <%= form.label :genre, 'Gênero' %>
        <%= select("book", "genre", [["Conto", "CONTO"], ["Ensaio", "ENSAIO"], ["Epopeia", "EPOPEIA"], ["Romance", "ROMANCE"], ["Novela", "NOVELA"]]) %>
      </div>

      <div class="form-group col-md-6 offset-md-3">
        <%= form.submit 'Cadastrar livro', class: "btn btn-primary" %>
      </div>
    </div>
  <% end %>
</div>

app/views/books/list_search.html.erb
<div class="container" style="height: 100%;">
  <div class="section-title">
    <h1>Livros Disponiveis</h1>
  </div>
  <div class="card-deck" style="height: 100%;">
    <div class="row" style="width: 100%;">
      <% @books.each do |book| %>
        <div class="book-card col-md-4">
          <div class="card" >
            <div class="card-header">
              <%= book.title %>
            </div>
            <div class="card-body">
              <p class="card-text"><%= book.author %></p>
              <p><%= link_to "Detalhe do livro", book_path(book) %></p>
              <p><%= link_to "Livro de #{book.user.nickname}", user_path(book.user) %></p>
            </div>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/books/new.html.erb
<div class="section-title">
  <h1>Novo livro</h1>
</div>

<%= render 'form', book: @book %>

app/views/books/search.html.erb
<div class="container input-form">
  <div class="section-title">
    <h1>Busca de livros para troca</h1>
  </div>
  <%= form_tag books_list_search_path, class: "row", method: "get" do %>
    <div class="form-group col-md-6 offset-md-3">
      <%= label_tag(:title, "Titulo:") %>
      <%= text_field_tag(:title, "", class: "form-control") %>
    </div>
    <div class="col-md-2 offset-md-3">
      <%= submit_tag("Buscar", class: "btn btn-primary") %>
    </div>
  <% end %>
</div>

app/views/books/shelf.html.erb
<div class="container" style="height: 100%;">
  <div class="section-title">
    <h1>Estante de livros</h1>
  </div>
  <div class="card-deck" style="height: 100%;">
    <div class="row" style="width: 100%;">
      <% @books.each do |book| %>
        <div class="book-card col-md-4">
          <div class="card" >
            <div class="card-header">
              <%= book.title %>
            </div>
            <div class="card-body">
              <p class="card-text"><%= book.author %></p>
              <%= link_to "Detalhes do livro", book_path(book) %>
              <p>
                <% if book.tradable %>
                  <%= link_to "Remover livro de trocas", remove_trade_path(book) %>
                <% else %>
                  <%= link_to "Disponibilizar para trocas", setup_trade_path(book) %>
                <% end %>
              </p>
              <p><%= link_to "Deletar livro", book_path(book), method: :delete %></p>
              <p><%= link_to "Escrever resenha", new_book_review_path(book) %></p>
            </div>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/books/show.html.erb
<div class="container" style="height: 100%;">
  <div class="section-title">
    <h1>Detalhes do livro</h1>
  </div>
  <div class="row" style="align-items: center;">
    <div class="card offset-md-3 col-md-6">
      <ul class="list-group list-group-flush">
        <li class="list-group-item"><strong>Título:</strong> <%= @book.title %></li>
        <li class="list-group-item"><strong>Autor:</strong><%= @book.author %></li>
        <li class="list-group-item"><strong>Data de publicação:</strong><%= @book.publication_date %></li>
        <li class="list-group-item"><strong>Código:</strong><%= @book.code %></li>
        <li class="list-group-item"><strong>Gênero:</strong><%= @book.genre %></li>
      </ul>
    </div>
  </div>
  <div class="section-title">
    <h1> Resenhas</h1>
  </div>
  <div class="card-deck">
    <div class="row">
      <% @book.reviews.each do |review| %>
      <div class="book-card col-md-10 offset-md-1" >
        <div class="card" >
          <div class="card-body">
            <h5 class="card-title"><%= review.title %></h5>
            <p class="card-text"><%= review.body %></p>
            <%= link_to "Resenha de #{review.user.nickname}", user_path(review.user) %>
          </div>
        </div>
      </div>
      <% end %>
    </div>
  </div>
</div>