config/routes.rb
Rails.application.routes.draw do
  root to: "welcome#home", as: "login_form"

  scope :users do
    get "/home", to: "users#home", as: "users_home"
    get "/search", to: "users#search", as: "users_search"
  end
  resources :users, only: [:index, :new, :show, :create]

  post "/login", to: "welcome#login", as: "login"
  get "/logout", to: "welcome#logout", as: "logout"

  scope :books do
    get "/search", to: "books#search", as: "books_search"
    get "/list_search", to: "books#list_search", as: "books_list_search"
    get "/:id/setup-trade", to: "books#setup_trade", as: "setup_trade"
    get "/:id/remove-trade", to: "books#remove_trade", as: "remove_trade"
  end

  resources :books, only: [:create, :new, :show, :destroy, :index] do
    resources :reviews, shallow: true
  end

  get "/shelf", to: "books#shelf", as: "shelf"
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>EstanteVirtual</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% if current_user.present? %>
      <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <a class="navbar-brand" href="#">Estante Virtual</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
              <%= link_to "Home", users_home_path, class: "nav-link" %>
            </li>
            <li class="nav-item active">
              <%= link_to "Estante", shelf_path, class: "nav-link" %>
            </li>
            <li class="nav-item active">
              <%= link_to "Cadastrar livro", new_book_path, class: "nav-link" %>
            </li>
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                Busca
              </a>
              <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                <%= link_to "Buscar usuário", users_search_path, class: "dropdown-item" %>
                <%= link_to "Buscar livro para troca", books_search_path, class: "dropdown-item" %>
              </div>
            </li>
            <li class="nav-item active">
              <%= link_to "Sair", logout_path, class: "nav-link" %>
            </li>
          </ul>
          <%= form_tag books_list_search_path, class: "form-inline my-2 my-lg-0", method: "get" do %>
            <%= text_field_tag(:title, "", class: "form-control mr-sm-2", placeholder: "Livro para troca") %>
            <%= submit_tag("Buscar troca", class: "btn btn-outline-success my-2 my-sm-0") %>
          <% end %>
        </div>
      </nav>
    <% end %>
    <% %w[error success notice].each do |type| %>
      <% if flash[type].present? %>
        <div class="alert alert-<%= type %> col-md-10 offset-md-1 text-center" role="alert">
          <%= flash[type] %>
          <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
      <% end %>
    <% end %>
    <%= yield %>
  </body>
</html>